# Generated by Django 5.1.3 on 2024-11-14 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvupload',
            old_name='file',
            new_name='csv_file',
        ),
    ]
