# Generated by Django 5.1.3 on 2024-11-14 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0002_rename_file_csvupload_csv_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvupload',
            old_name='csv_file',
            new_name='file',
        ),
    ]
